export const DASHDATA_SUCCESS = "DASHDATA_SUCCESS";
export const DASHDATA_FAIL = "DASHDATA_FAIL";
export const LOGIN_INFO_SUCCESS = "LOGIN_INFO_SUCCESS";
export const LOGIN_INFO_FAIL = "LOGIN_INFO_FAIL";
